version: '3'
services:
  colors_tropes_app:
    image: registry.uat.viacom18.com:5000/colors_tropes:uat
    # ports:
      #  - "5508:8501"
    volumes:
      - colors_tropes-volume-app-log:/app/logs/app
      - colors_tropes-volume-app-data:/app/data
    environment:
      - LOG_LEVEL=INFO
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PROTOCOL=${REDIS_PROTOCOL}
      - BASE_URL=${BASE_URL}
      - HEALTH_CHECK_URL=${HEALTH_CHECK_URL}
      - ACTIVITY_URL=${ACTIVITY_URL}
      - VERIFY_AUTH_URL=${VERIFY_AUTH_URL}
      - LOGOUT_URL=${LOGOUT_URL}
      - LOGIN_URL=${LOGIN_URL}
      - APPLICATION_NAME=${APPLICATION_NAME}
      - FORCE_AUTH=false
      - LOG_API_ENDPOINT=${LOG_API_ENDPOINT}
      - LOG_TYPE=api,file
    
    depends_on:
      - redis
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  colors_tropes_nginx:
    image: registry.uat.viacom18.com:5000/colors_tropes:uat-re-proxy
    container_name: colors_tropes-nginx-proxy
    depends_on:
        - colors_tropes_app
    volumes:
      - colors_tropes-volume-app-log:/app/logs/app
      - colors_tropes-volume-nginx:/app/logs/nginx
    ports:
      - "5508:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]  
  
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1

    
volumes:
  colors_tropes-volume-app-log:
    driver: local
  colors_tropes-volume-app-data:
    driver: local
  colors_tropes-volume-nginx:
    driver: local