user  nginx;
worker_processes  auto;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    upstream colors_tropes_servers {
        server colors_tropes_app:8501;
    }

    log_format main '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $bytes_sent '
                       '"$http_referer" "$http_user_agent" "$gzip_ratio"';
    
    access_log /app/logs/nginx/access.txt main buffer=32k;
    error_log /app/logs/nginx/error.txt;

    server {
        listen 80;

        client_max_body_size 50m;

        # Serve log files
        location /colors-tropes/logs/ {
            autoindex on;  # Enable directory listing for logs
            access_log off;  # Turn off access logging for this location
            alias /app/logs/;  # Point to the logs directory in the container
        }

        location /colors-tropes/_stcore/stream {
            proxy_pass http://music_cuesheet_servers;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }

        location /colors-tropes/ {
            proxy_pass http://colors_tropes_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        
    }

}